// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccess.Migrations
{
    [DbContext(typeof(ProductDbContext))]
    partial class ProductDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Models.Product", b =>
            {
                b.Property<int>("ProductId")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int");

                SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdProduct"));

                b.Property<string>("Name")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("StatusName")
                    .HasColumnType("nvarchar(1)");

                b.Property<string>("Stock")
                    .HasColumnType("nvarchar(40)");

                b.Property<string>("Descripcion")
                    .HasColumnType("nvarchar(max)");

                b.Property<string>("Price")
                    .HasColumnType("nvarchar(40)");

                b.Property<string>("Discount")
                    .HasColumnType("nvarchar(40)");

                b.Property<string>("FinalPrice")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("DateCreated")
                    .HasColumnType("datetime2");

                b.Property<string>("Description")
                    .HasColumnType("nvarchar(max)");

                b.Property<DateTime>("LastModified")
                    .HasColumnType("datetime2");


                b.HasKey("ProductId");

                b.ToTable("Products");
            });
#pragma warning restore 612, 618
        }
    }
}
